common: &common
  adapter: mysql2
  username: root
  password:
  pool: 5
  socket: /tmp/mysql.sock
  encoding: utf8
  host: localhost
  
production:
  database: wagn_production
  <<: *common  

development:
  database: wagn_development
  <<: *common

test:
  database: wagn_test
  <<: *common

cucumber:
  database: wagn_test
  <<: *common


