common: &common
  adapter: mysql
  username: root
#  password: password
  encoding: utf8
  host: localhost
  secret: YrDOFOmYJyFg2tTZykCbZjWYQUbKBt

development:
  database: wagn_development
  <<: *common

test:
  database: wagn_test
  <<: *common

cucumber:
  database: wagn_test
  <<: *common

production:
  database: wagn_production
  <<: *common
